services:
  tdd:
    build: .
    ports: 
      - 3000:3000
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: hello_darkness
      POSTGRES_USER: wot
      POSTGRES_DB: tdd